### ISSUE TITLE
Provide arguments to evalBash

### ISSUE THREAD

**Issue by adomingues** [holgerbrandl/kutils#3]
Hi @holgerbrandl,

is it possible to pass arguments to commands constructed with `evalBash`?

https://github.com/holgerbrandl/kutils/blob/master/src/main/kotlin/de/mpicbg/scicomp/kutils/Bash.kt#L14

The reason is that I want to pass an argument to this snippet of `star_align.kts`:

```kotlin
// Do reporting and perform bam correlation (but don't wait for the results)
evalBash("""
rend.R -e ${'$'}NGS_TOOLS/dge_workflow/star_qc.R .

# Condense counts into matrix
dge_star_counts2matrix
""")
```

Something along the lines of ($NEWARG):

```kotlin
// Do reporting and perform bam correlation (but don't wait for the results)
evalBash("""
rend.R -e ${'$'}NGS_TOOLS/dge_workflow/star_qc.R .

# Condense counts into matrix
dge_star_counts2matrix $NEWARG
""")
```

Basically I extended the function `dge_star_counts2matrix` to retrieve stranded counts (it takes only the first col of the star amtrix by default):
https://git.mpi-cbg.de/bioinfo/ngs_tools/blob/master/dge_workflow/dge_utils.sh#L391

This works fine if I call the bash function directly, but ideally I would be able to use it as part of `star_align.kts`. If this is not possible, no worries. It's not essential for the workflow, just nice to have.

Cheers,
António

**Comment by holgerbrandl** [comment]
Why not something along 
```
// from docopt param (in case it is exposed to to user as option)
val library = doArgs["library"])

// ..OR: calculated field that could be even null 
val library: Integer? = if(someTestCondition) 3 : null


evalBash("""
rend.R -e ${'$'}NGS_TOOLS/dge_workflow/star_qc.R .

# Condense counts into matrix
dge_star_counts2matrix ${library ?: ""}
""")
```

This is using https://kotlinlang.org/docs/reference/null-safety.html#elvis-operator and https://kotlinlang.org/docs/reference/basic-types.html#string-templates

`evalBash` accepts any string as an argument. It's up to you how to prepare it.

Feel welcome if i got the question mixed up/wrong?

**Comment by adomingues** [comment]
Thanks Holger! The missing piece of puzzle was `${library ?: ""}` -  that is exactly what I needed to know!
